In [36]:
import numpy as np
import  torch
a=torch.randn(2,4)
print(a)
print(a.shape)
print(a.type())
print(type(a))
print(isinstance(a,torch.IntTensor))
print(isinstance(a,torch.FloatTensor))

tensor([[-0.4826,  2.7383, -2.8546,  0.9479],
        [-1.0390, -0.8626, -0.1026, -0.4092]])
torch.Size([2, 4])
torch.FloatTensor
<class 'torch.Tensor'>
False
True


In [24]:
b=torch.tensor(2.1)
print(b)
print(b.shape)
print(b.size())

tensor(2.1000)
torch.Size([])
torch.Size([])


In [8]:
b=torch.tensor([2.1])
print(b.shape)
print(b.size())

torch.Size([1])
torch.Size([1])


In [2]:
b=torch.tensor([1.3,2.6])
b.shape

torch.Size([2])

In [27]:
torch.FloatTensor(1)

tensor([-2.3470e+10])

In [26]:
torch.FloatTensor(1).shape

torch.Size([1])

In [10]:
torch.FloatTensor(2)

tensor([0., 0.])

In [8]:
torch.tensor([3]).shape

torch.Size([1])

In [9]:
torch.tensor([3,1]).shape

torch.Size([2])

In [28]:
torch.FloatTensor(2).shape

torch.Size([2])

In [17]:
torch.FloatTensor(3)

tensor([-2.3470e+10,  4.5668e-41,  3.2650e-24])

In [21]:
torch.FloatTensor(3).shape

torch.Size([3])

In [19]:
torch.randn(2,4)

tensor([[-0.3734, -1.5454,  0.0581,  0.2323],
        [-1.0367, -1.0539, -0.4568, -0.0616]])

In [20]:
torch.randn(2,4).shape

torch.Size([2, 4])

In [22]:
torch.FloatTensor([[1.2,1.3,2.1],[3.2,2.5,1.6]])

tensor([[1.2000, 1.3000, 2.1000],
        [3.2000, 2.5000, 1.6000]])

In [23]:
torch.FloatTensor([[1.2,1.3,2.1],[3.2,2.5,1.6]]).shape

torch.Size([2, 3])

In [34]:
np.ones(2)

array([1., 1.])

In [32]:
np.ones(2).shape

(2,)

In [14]:
torch.from_numpy(np.ones(2))

tensor([1., 1.], dtype=torch.float64)

In [31]:
torch.from_numpy(np.ones(2)).shape

torch.Size([2])

In [37]:
torch.FloatTensor([[1.2,1.3,2.1],[3.2,2.5,1.6]])

tensor([[1.2000, 1.3000, 2.1000],
        [3.2000, 2.5000, 1.6000]])

In [38]:
torch.FloatTensor([[1.2,1.3,2.1],[3.2,2.5,1.6]]).shape

torch.Size([2, 3])

In [39]:
torch.FloatTensor([[1.2,1.3,2.1],[3.2,2.5,1.6]]).shape[0]

2

In [40]:
torch.FloatTensor([[1.2,1.3,2.1],[3.2,2.5,1.6]]).shape[1]

3

In [42]:
torch.FloatTensor([[1.2,1.3,2.1],[3.2,2.5,1.6]]).size(0)

2

In [43]:
torch.FloatTensor([[1.2,1.3,2.1],[3.2,2.5,1.6]]).size(1)

3

In [44]:
torch.FloatTensor(
     [
         [[1.2,1.3,2.1],[3.2,2.5,1.6]],
         [[3.6,6.3,5.1],[7.2,3.5,4.6]]
     ])

tensor([[[1.2000, 1.3000, 2.1000],
         [3.2000, 2.5000, 1.6000]],

        [[3.6000, 6.3000, 5.1000],
         [7.2000, 3.5000, 4.6000]]])

In [45]:
torch.FloatTensor(
     [
         [[1.2,1.3,2.1],[3.2,2.5,1.6]],
         [[3.6,6.3,5.1],[7.2,3.5,4.6]]
     ]).shape

torch.Size([2, 2, 3])

In [46]:
torch.FloatTensor(
     [
         [[1.2,1.3,2.1],[3.2,2.5,1.6]],
         [[3.6,6.3,5.1],[7.2,3.5,4.6]]
     ]).shape[0]

2

In [49]:
torch.FloatTensor(
     [
         [[1.2,1.3,2.1],[3.2,2.5,1.6]],
         [[3.6,6.3,5.1],[7.2,3.5,4.6]]
     ]).shape[1]

2

In [50]:
torch.FloatTensor(
     [
         [[1.2,1.3,2.1],[3.2,2.5,1.6]],
         [[3.6,6.3,5.1],[7.2,3.5,4.6]]
     ]).shape[2]

3

In [51]:
a=torch.FloatTensor(
     [
         [[1.2,1.3,2.1],[3.2,2.5,1.6]],
         [[3.6,6.3,5.1],[7.2,3.5,4.6]]
     ])
a[0]

tensor([[1.2000, 1.3000, 2.1000],
        [3.2000, 2.5000, 1.6000]])

In [52]:
a=torch.FloatTensor(
     [
         [[1.2,1.3,2.1],[3.2,2.5,1.6]],
         [[3.6,6.3,5.1],[7.2,3.5,4.6]]
     ])
a[1]

tensor([[3.6000, 6.3000, 5.1000],
        [7.2000, 3.5000, 4.6000]])

In [3]:
a=torch.FloatTensor(
     [
         [[1.2,1.3,2.1],[3.2,2.5,1.6]],
         [[3.6,6.3,5.1],[7.2,3.5,4.6]]
     ])
list(a.shape)

[2, 2, 3]

In [5]:

a=torch.rand(9,1,28,28)#四维矩阵适合卷积神经网络
a
print('你好')
print('你好吗')

你好


In [5]:
import torch
a=torch.rand(9,1,28,28)#四维矩阵适合卷积神经网络
a.numel()

7056

In [6]:
a=torch.rand(9,1,28,28)#四维矩阵适合卷积神经网络
a.dim()

4

In [9]:
#从numpy引入tensor
import numpy
a=numpy.array([2,3.2])
torch.from_numpy(a)

tensor([2.0000, 3.2000], dtype=torch.float64)

In [10]:
a=numpy.ones([2,3])#值为1而取名ones
torch.from_numpy(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [13]:
#Tensor接受shape数据维度;tensor接受具体数据numpy,列表,
torch.tensor([3.1,3.6])

tensor([3.1000, 3.6000])

In [16]:
#Tensor接受shape数据维度;tensor接受具体数据numpy,列表,
torch.FloatTensor(3,4)

tensor([[3.3995e-09, 3.0651e-41, 3.4179e-09, 3.0651e-41],
        [8.9683e-44, 0.0000e+00, 1.1210e-43, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 3.5073e-09, 3.0651e-41]])

In [17]:
#Tensor接受shape数据维度;tensor接受具体数据numpy,列表,
#Tensor使用的默认数据类型
torch.FloatTensor(2,3,4)

tensor([[[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 9.1835e-41, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 6.0995e+14, 4.5668e-41]]])

In [14]:
#Tensor也可以接受现成数据的情况,尽量少用
torch.FloatTensor([3.1,3.6])

tensor([3.1000, 3.6000])

In [19]:
torch.empty(2,3)#生成未初始化的数据

tensor([[2.5516e+19, 4.5668e-41, 2.5516e+19],
        [4.5668e-41, 4.4842e-44, 0.0000e+00]])

In [20]:
torch.empty(1)#生成未初始化的数据

tensor([2.5516e+19])

In [24]:
torch.set_default_tensor_type(torch.DoubleTensor)
torch.tensor([5.2,3]).type()

'torch.DoubleTensor'

In [26]:
torch.set_default_tensor_type(torch.DoubleTensor)
torch.tensor([5,3]).type()

'torch.LongTensor'

In [28]:
torch.rand(2,3)#生成随机的均匀的0-1之间的数据

tensor([[0.2178, 0.1104, 0.6771],
        [0.8065, 0.3951, 0.8023]])

In [29]:
a=torch.rand(4,3)#生成随机的均匀的0-1之间的数据
torch.rand_like(a)
#rand_like更加通用可以获取一个shape来生成随机的均匀的0-1之间的数据

tensor([[0.4504, 0.9669, 0.4353],
        [0.1817, 0.2417, 0.0922],
        [0.5074, 0.3863, 0.6724],
        [0.4532, 0.9165, 0.6650]])

In [30]:
torch.rand(4,3)#生成正态分布N(0,1)的0-1之间的数据

tensor([[0.2103, 0.9001, 0.1816],
        [0.0797, 0.1690, 0.7149],
        [0.2505, 0.9953, 0.8008],
        [0.5319, 0.1053, 0.5546]])

In [31]:
torch.full([2,3],6)#全部值为6

tensor([[6, 6, 6],
        [6, 6, 6]])

In [32]:
torch.full([],6)#标量

tensor(6)

In [33]:
torch.full([1],6)#

tensor([6])

In [34]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
torch.arange(0,10,2)#torch里面不建议使用range

tensor([0, 2, 4, 6, 8])

In [37]:
torch.linspace(0,10,steps=4)#4等分

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])

In [38]:
torch.linspace(0,10,steps=20)#20等分

tensor([ 0.0000,  0.5263,  1.0526,  1.5789,  2.1053,  2.6316,  3.1579,  3.6842,
         4.2105,  4.7368,  5.2632,  5.7895,  6.3158,  6.8421,  7.3684,  7.8947,
         8.4211,  8.9474,  9.4737, 10.0000])

In [39]:
torch.logspace(0,-1,steps=10)#*10

tensor([1.0000, 0.7743, 0.5995, 0.4642, 0.3594, 0.2783, 0.2154, 0.1668, 0.1292,
        0.1000])

In [40]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [41]:
torch.eye(2, 3)#对角线全为1

tensor([[1., 0., 0.],
        [0., 1., 0.]])

In [42]:
torch.eye(3, 3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [48]:
a=torch.rand(4,3,28,28)#bitchsize,channel,long,height
a[0].shape

torch.Size([3, 28, 28])

In [49]:
a=torch.rand(4,3,28,28)#bitchsize,channel,long,height
a[0,0].shape

torch.Size([28, 28])

In [50]:
a=torch.rand(4,3,28,28)#bitchsize,channel,long,height
a[0,0,15,20].shape#像素点标量

torch.Size([])

In [51]:
a=torch.rand(4,3,28,28)#bitchsize,channel,long,height
a[0,0,15,20]#像素点标量

tensor(0.4382)

In [52]:
a=torch.rand(4,3,28,28)#bitchsize,channel,long,height
a[:2].shape#取两张

torch.Size([2, 3, 28, 28])

In [54]:
a=torch.rand(4,3,28,28)#bitchsize,channel,long,height
a[:2,:1].shape#取两张的一个通道

torch.Size([2, 1, 28, 28])

In [55]:
a=torch.rand(4,3,28,28)#bitchsize,channel,long,height
a[:2,:1,:,:].shape#取两张的一个通道

torch.Size([2, 1, 28, 28])

In [57]:
a=torch.rand(4,3,28,28)#bitchsize,channel,long,height
a[:2,:-1,:,:].shape#-1:从最后一个元素取到最后,就是取了一个元素
#正向从0开始,反向从-1开始

tensor([[[[0.4447, 0.4781, 0.7509,  ..., 0.0457, 0.1021, 0.7490],
          [0.8691, 0.9869, 0.0925,  ..., 0.3882, 0.7877, 0.5402],
          [0.6129, 0.3195, 0.3560,  ..., 0.8103, 0.8543, 0.7815],
          ...,
          [0.8656, 0.3143, 0.6905,  ..., 0.6107, 0.2750, 0.9405],
          [0.0795, 0.3790, 0.7687,  ..., 0.7279, 0.9212, 0.9394],
          [0.6446, 0.1612, 0.7189,  ..., 0.5325, 0.8837, 0.9191]],

         [[0.8531, 0.6746, 0.6651,  ..., 0.5806, 0.9308, 0.5945],
          [0.1172, 0.8937, 0.2230,  ..., 0.6722, 0.6970, 0.3900],
          [0.9972, 0.3366, 0.6393,  ..., 0.9663, 0.2771, 0.2510],
          ...,
          [0.8561, 0.1801, 0.2561,  ..., 0.9915, 0.8435, 0.2286],
          [0.9930, 0.1559, 0.7491,  ..., 0.1816, 0.0431, 0.6269],
          [0.3632, 0.4005, 0.9515,  ..., 0.2259, 0.2981, 0.9866]]],


        [[[0.0385, 0.0541, 0.9255,  ..., 0.4051, 0.1651, 0.2283],
          [0.0067, 0.6564, 0.8748,  ..., 0.4772, 0.5711, 0.3900],
          [0.7215, 0.6595, 0.1045,  ...,

In [58]:
a=torch.rand(4,3,28,28)#bitchsize,channel,long,height
a[:2,:-1,0:28:2,0:28:2].shape#0:28:2隔行采样
#正向从0开始,反向从-1开始

torch.Size([2, 2, 14, 14])

In [ ]:
#index_select可以对某个维度针对性采样

In [59]:
a=torch.rand(4,3,28,28)#bitchsize,channel,long,height
a.index_select(2,torch.arange(7)).shape


torch.Size([4, 3, 7, 28])

In [60]:
a=torch.rand(4,3,28,28)#bitchsize,channel,long,height
a[...].shape

torch.Size([4, 3, 28, 28])

In [61]:
a=torch.rand(4,3,28,28)#bitchsize,channel,long,height
a[1,...].shape

torch.Size([3, 28, 28])

In [62]:
a=torch.rand(4,3,28,28)#bitchsize,channel,long,height
a[:,1,...].shape#...表示其余的每个维度都选取

torch.Size([4, 28, 28])

In [63]:
a=torch.rand(4,3,28,28)#bitchsize,channel,long,height
a[:2,1,...].shape

torch.Size([2, 28, 28])

In [65]:
a=torch.rand(4,3,28,28)#bitchsize,channel,long,height
a[...,:16].shape

torch.Size([4, 3, 28, 16])

In [66]:
a=torch.rand(4,3,28,28)#bitchsize,channel,long,height
a[...,:20,:16].shape

torch.Size([4, 3, 20, 16])

In [67]:
a=torch.rand(4,3,28,28)#bitchsize,channel,long,height
a[:2,...,:16].shape

torch.Size([2, 3, 28, 16])

In [ ]:
#masked_select()可以根据mask来选择元素


In [71]:
src=torch.rand(2,3)
torch.take(src,torch.tensor([0,2,5]))#take将tensor打平,再索引元素

tensor([0.2574, 0.5106, 0.9052])

In [73]:
#view
#bitchsize,channel,long,height
a=torch.rand(4,1,28,28)
a.view(4,28*28)#适用于全链接层的输入

tensor([[0.0456, 0.1177, 0.0224,  ..., 0.3625, 0.1895, 0.7850],
        [0.0815, 0.6169, 0.2712,  ..., 0.6650, 0.3968, 0.8011],
        [0.0832, 0.7407, 0.5257,  ..., 0.0629, 0.6883, 0.6146],
        [0.7596, 0.2585, 0.8046,  ..., 0.2533, 0.8347, 0.2172]])

In [74]:
#view
#bitchsize,channel,long,height
a=torch.rand(4,3,28,28)
a.view(4,28*28)#适用于全链接层的输入

RuntimeError: shape '[4, 784]' is invalid for input of size 9408

In [75]:
#view
#bitchsize,channel,long,height
a=torch.rand(4,1,28,28)#维度为1时有没有看不影响数据量,而是影响对数据的分组理解
a.view(4,28*28)#将一张图看成一行28*28的行,适用于全链接层的输入
a.view(4*28,28)#以行为单位考察,有4*28行

tensor([[0.2049, 0.4424, 0.9131,  ..., 0.2499, 0.9601, 0.3144],
        [0.1696, 0.3707, 0.8271,  ..., 0.9318, 0.2526, 0.2913],
        [0.4637, 0.9646, 0.9386,  ..., 0.6793, 0.5893, 0.9408],
        ...,
        [0.1143, 0.2069, 0.7124,  ..., 0.9967, 0.2573, 0.8558],
        [0.3003, 0.5629, 0.2751,  ..., 0.7107, 0.1229, 0.3117],
        [0.0498, 0.7953, 0.0384,  ..., 0.1650, 0.7921, 0.3981]])

In [ ]:
a=torch.rand(4,1,28,28)
a.view(4*1,28,28)#将一张图看成一行28*28的矩阵,适用于全链接层的输入
#view会丢失维度存储信息,恢复时需要额外的信息才可以


In [78]:
a=torch.rand(4,1,28,28)
a.unsqueeze(0)
a.unsqueeze(0).shape#多加了一个括号扩起来


torch.Size([1, 4, 1, 28, 28])

In [79]:
a=torch.rand(4,1,28,28)
a.unsqueeze(0)
a.unsqueeze(-1).shape#在索引-1之前插入

torch.Size([4, 1, 28, 28, 1])

In [82]:
a=torch.rand(4,1,28,28)
a.unsqueeze(0)
a.unsqueeze(-2).shape#多加了一个括号扩起来

torch.Size([4, 1, 28, 1, 28])

In [84]:
#squeeze压缩,抛弃维度信息不关心,保留数据本身
#[1,32,1,1]=>[32]原来32个通道各有一个数据,现在仍然有32个数据,不管那一类
a=torch.rand(1,32,1,1)
a.squeeze().shape#不传递参数表示压缩所有为1的维度

torch.Size([32])

In [85]:
#squeeze压缩,抛弃维度信息不关心,保留数据本身
#[1,32,1,1]=>[32]原来32个通道各有一个数据,现在仍然有32个数据,不管那一类
a=torch.rand(1,32,1,1)
a.squeeze(0).shape

torch.Size([32, 1, 1])

In [86]:
#squeeze压缩,抛弃维度信息不关心,保留数据本身
#[1,32,1,1]=>[32]原来32个通道各有一个数据,现在仍然有32个数据,不管那一类
a=torch.rand(1,32,1,1)
a.squeeze(-1).shape

torch.Size([1, 32, 1])

In [88]:
#维度拓展
a=torch.rand(1,32,1,1)
b=torch.rand(4,32,14,14)#原来为1的维度才可以拓展,不为1没法复制
a.expand(4,32,14,14).shape

torch.Size([4, 32, 14, 14])

In [89]:
#维度拓展
a=torch.rand(1,32,4,1)
b=torch.rand(4,32,14,14)#显然4=>14没法多次复制实现
a.expand(4,32,14,14).shape

RuntimeError: The expanded size of the tensor (14) must match the existing size (4) at non-singleton dimension 2.  Target sizes: [4, 32, 14, 14].  Tensor sizes: [1, 32, 4, 1]

In [90]:
#repeat
a=torch.rand(1,32,4,1)
a.repeat(4,1,2,14).shape

torch.Size([4, 32, 8, 14])

In [92]:
#矩阵转置
a=torch.rand(3,4)
a.t()#只是用于矩阵

tensor([[0.6422, 0.7621, 0.9805],
        [0.7984, 0.5452, 0.8382],
        [0.4120, 0.4262, 0.0550],
        [0.9439, 0.9548, 0.8385]])

In [96]:
#transpose
a=torch.rand(4,3,32,32)
a.shape
a.transpose(1,3).shape#交换1,3维度


torch.Size([4, 32, 32, 3])

In [100]:
#transpose
a=torch.rand(4,3,32,32)
a.shape
a.transpose(1,3).view(4,3*32*32).view(4,3,32,32)
#维度变换导致数据不连续

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [101]:
#transpose
a=torch.rand(4,3,32,32)
a.shape
a.transpose(1,3).contiguous().view(4,3*32*32).view(4,3,32,32)#contiguous()实现连续化,#不过还是错误的

tensor([[[[4.3067e-01, 8.3133e-02, 6.0404e-01,  ..., 2.2435e-02,
           1.8692e-01, 8.7619e-01],
          [4.8460e-01, 1.6701e-01, 4.2860e-01,  ..., 1.3284e-01,
           9.2028e-01, 7.2683e-01],
          [4.4439e-01, 3.3718e-03, 4.0584e-01,  ..., 4.8194e-02,
           4.9164e-01, 6.7254e-01],
          ...,
          [5.1805e-01, 9.0596e-03, 8.1282e-01,  ..., 9.0021e-01,
           4.8700e-01, 3.0087e-01],
          [3.5393e-01, 2.4444e-01, 2.8306e-01,  ..., 7.5470e-02,
           4.7585e-01, 2.4910e-01],
          [6.4154e-01, 7.3146e-03, 9.9149e-01,  ..., 8.1013e-01,
           4.4816e-01, 9.9249e-01]],

         [[5.8441e-01, 4.6009e-01, 7.3179e-01,  ..., 7.2992e-02,
           8.0750e-01, 1.6409e-01],
          [5.0579e-02, 9.4801e-01, 2.9821e-01,  ..., 7.2075e-01,
           1.1616e-01, 4.2064e-01],
          [6.0547e-01, 3.3937e-01, 3.0030e-01,  ..., 9.1416e-01,
           8.5680e-01, 1.6111e-01],
          ...,
          [7.8615e-01, 8.2155e-01, 1.5964e-01,  ..., 2.5458

In [102]:
#transpose
a=torch.rand(4,3,32,32)
a.shape
a.transpose(1,3).contiguous().view(4,3*32*32).view(4,32,32,3).transpose(1,3)
#跟踪维度信息,这样就完全不变了

tensor([[[[5.4828e-01, 8.3180e-01, 9.5768e-01,  ..., 6.5977e-01,
           3.7466e-01, 8.3000e-01],
          [1.8124e-01, 8.8283e-01, 7.2073e-01,  ..., 2.2556e-01,
           3.0337e-02, 7.9313e-01],
          [5.8105e-02, 7.7306e-01, 1.5377e-01,  ..., 4.7403e-01,
           9.2103e-01, 4.1398e-01],
          ...,
          [2.5378e-01, 5.2989e-01, 9.5435e-01,  ..., 3.3101e-01,
           3.8319e-01, 2.6550e-01],
          [6.6456e-01, 3.8422e-01, 7.7271e-02,  ..., 5.9150e-01,
           2.1570e-01, 5.1886e-01],
          [9.8543e-01, 2.3678e-01, 1.5065e-01,  ..., 9.8475e-01,
           4.5740e-01, 7.1265e-01]],

         [[4.4879e-01, 1.2950e-02, 7.1129e-01,  ..., 9.9164e-01,
           1.7414e-01, 4.5326e-01],
          [3.1828e-01, 9.3233e-01, 5.4462e-01,  ..., 5.2155e-01,
           5.7119e-01, 1.9552e-01],
          [3.5620e-01, 1.2074e-01, 4.8139e-02,  ..., 8.3267e-01,
           1.9583e-01, 3.1247e-01],
          ...,
          [8.1292e-02, 7.3352e-01, 2.2487e-01,  ..., 4.2667

In [105]:
#permute
a=torch.rand(4,3,25,32)
a.permute(1,2,3,0).shape

torch.Size([3, 25, 32, 4])

In [106]:
#cat拼接
a=torch.rand(4,3,20)
b=torch.rand(6,3,20)
torch.cat([a,b],dim=0).shape
#dim要一样,后面的维度一样,外部盒子一样内部才有机会合并

torch.Size([10, 3, 20])

In [112]:
#stack维度必须完全一样
a=torch.rand(4,3,20)
b=torch.rand(4,3,20)
torch.stack([a,b],dim=1).shape

torch.Size([4, 2, 3, 20])

In [115]:
c=torch.rand(4,3,20)
aa,bb=c.split([1,3],dim=0)
aa.shape,bb.shape

(torch.Size([1, 3, 20]), torch.Size([3, 3, 20]))

In [116]:
c=torch.rand(4,3,20)
aa,bb=c.split([1,2],dim=1)
aa.shape,bb.shape

(torch.Size([4, 1, 20]), torch.Size([4, 2, 20]))

In [123]:
c=torch.rand(4,3,20)
aa,bb=c.split(3,dim=0)#每块为3,不够的一块
aa.shape,bb.shape

(torch.Size([3, 3, 20]), torch.Size([1, 3, 20]))

In [122]:
c=torch.rand(6,3,20)
aa,bb,dd=c.split(2,dim=0)#每块为2
aa.shape,bb.shape,dd.shape

ValueError: too many values to unpack (expected 3)

In [125]:
#按数量拆分
c=torch.rand(6,3,20)
aa,bb,dd=c.chunk(3,dim=0)#
aa.shape,bb.shape,dd.shape

(torch.Size([2, 3, 20]), torch.Size([2, 3, 20]), torch.Size([2, 3, 20]))

In [126]:
#按数量拆分
c=torch.rand(6,3,20)
aa,bb,dd=c.chunk(3,dim=1)#
aa.shape,bb.shape,dd.shape

(torch.Size([6, 1, 20]), torch.Size([6, 1, 20]), torch.Size([6, 1, 20]))

In [127]:
#按数量拆分
c=torch.rand(6,3,20)
aa,bb,dd=c.chunk(3,dim=2)#
aa.shape,bb.shape,dd.shape

(torch.Size([6, 3, 7]), torch.Size([6, 3, 7]), torch.Size([6, 3, 6]))

In [130]:
#加法
a=torch.rand(3,4)
print(a)
b=torch.rand(4)#自动broadcast
print(b)
a+b

tensor([[0.2200, 0.6658, 0.9291, 0.0547],
        [0.6090, 0.8269, 0.1153, 0.2080],
        [0.7866, 0.4386, 0.6425, 0.2577]])
tensor([0.4405, 0.4444, 0.4934, 0.8268])


tensor([[0.6604, 1.1102, 1.4224, 0.8815],
        [1.0494, 1.2713, 0.6087, 1.0348],
        [1.2270, 0.8830, 1.1359, 1.0846]])

In [131]:
#加法,类似有sub,mul,div,注意元素相乘和矩阵相乘的区别
a=torch.rand(3,4)
print(a)
b=torch.rand(4)#自动broadcast
print(b)
torch.add(a,b)

tensor([[0.2416, 0.4702, 0.6719, 0.0831],
        [0.4038, 0.1319, 0.1636, 0.8846],
        [0.9285, 0.9121, 0.5395, 0.8212]])
tensor([0.7156, 0.3621, 0.0325, 0.3718])


tensor([[0.9572, 0.8323, 0.7045, 0.4548],
        [1.1194, 0.4940, 0.1962, 1.2564],
        [1.6441, 1.2742, 0.5720, 1.1929]])

In [139]:
a=torch.tensor([[3,2],[1,2]])
print(a)
b=torch.tensor([[1,2],[2,2]])
print(b)
print(a.mm(b))
print(a.matmul(b))
print(a*b)
print(a@b)
#mm,matmul,@三者一样

tensor([[3, 2],
        [1, 2]])
tensor([[1, 2],
        [2, 2]])
tensor([[ 7, 10],
        [ 5,  6]])
tensor([[ 7, 10],
        [ 5,  6]])
tensor([[3, 4],
        [2, 4]])
tensor([[ 7, 10],
        [ 5,  6]])


In [143]:
#降维
x=torch.rand(4,784)
w=torch.rand(512,784)
y=(x@w.t()).shape
print(y)
#w.t()降维矩阵
w2=torch.rand(64,512)
y2=(x@w.t()@w2.t()).shape
print(y2)
w3=torch.rand(10,64)
y3=(x@w.t()@w2.t()@w3.t()).shape
print(y3)
#数据在tensor中流动,tensorflow

torch.Size([4, 512])
torch.Size([4, 64])
torch.Size([4, 10])


In [147]:
#三维矩阵,四维矩阵乘法
a=torch.rand(4,3,12,64)
b=torch.rand(4,3,64,4)
a.matmul(b)
#mm会报错,对于高维矩阵,要用matmul
#matmul是后两维度相乘,就是多个矩阵对并行相乘


tensor([[[[18.7279, 14.7107, 18.4394, 15.6507],
          [19.1696, 16.6734, 18.9103, 16.6015],
          [18.8771, 14.1585, 17.3858, 14.7576],
          [17.3598, 14.8063, 18.6357, 15.9805],
          [16.5534, 13.9745, 16.7825, 14.5054],
          [17.5820, 16.0427, 16.8012, 14.7147],
          [16.9087, 16.5778, 18.2923, 13.4523],
          [18.2601, 15.7008, 17.6513, 16.2957],
          [17.1674, 15.1047, 19.2119, 14.9162],
          [17.6090, 14.7501, 18.6883, 15.3758],
          [16.1328, 13.0522, 15.3556, 13.8331],
          [16.5882, 15.1239, 18.1456, 15.7856]],

         [[17.7835, 16.3259, 16.4364, 15.1189],
          [15.6879, 14.0212, 13.6035, 12.3450],
          [16.8754, 14.4348, 16.3223, 13.8010],
          [18.3611, 15.3241, 15.9442, 13.4834],
          [17.4579, 14.8192, 15.4611, 13.7239],
          [17.1787, 15.8363, 17.2659, 14.1529],
          [18.4845, 14.7949, 16.4287, 15.3305],
          [17.0696, 15.7756, 16.0140, 13.0160],
          [17.0211, 14.7502, 16.5364, 

In [148]:
a=torch.rand(4,3,12,64)
b=torch.rand(4,1,64,4)
#先转换至(4,3,64,4),再矩阵相称
a.matmul(b)

tensor([[[[17.6791, 16.5329, 17.7322, 14.2755],
          [16.8261, 16.0999, 15.6053, 14.0312],
          [16.9536, 17.7834, 16.3790, 14.8252],
          [16.8188, 17.8827, 16.8425, 15.3597],
          [20.2786, 17.2437, 18.1378, 15.0270],
          [16.0006, 17.3413, 17.0755, 15.0517],
          [17.7110, 15.5447, 16.8860, 15.2984],
          [16.4113, 16.1740, 17.2216, 13.9614],
          [16.3866, 15.9782, 15.5784, 14.2969],
          [13.3035, 12.2432, 13.0641, 10.8445],
          [17.8015, 16.8325, 17.1840, 14.8672],
          [16.8763, 17.1841, 16.5568, 15.3770]],

         [[17.4315, 16.7569, 16.7822, 16.0238],
          [16.7256, 17.6839, 17.6801, 14.6609],
          [16.0267, 14.4685, 15.9524, 13.4161],
          [17.5120, 16.9284, 17.4674, 15.9492],
          [19.3057, 18.4845, 18.5468, 15.8730],
          [16.8840, 16.4994, 16.2741, 14.7507],
          [15.6611, 17.4749, 15.7679, 14.4022],
          [19.0372, 19.8527, 18.9184, 17.5505],
          [15.4764, 16.9339, 16.1043, 

In [160]:
a=torch.full([2,2],3)#全为3
print(a.pow(2))
print(a**2)
print(a**3)
print(torch.sqrt(a.to(torch.double)))#平方跟
print(torch.rsqrt(a.to(torch.double)))#平方跟的倒数
print(a**(0.5))

tensor([[9, 9],
        [9, 9]])
tensor([[9, 9],
        [9, 9]])
tensor([[27, 27],
        [27, 27]])
tensor([[1.7321, 1.7321],
        [1.7321, 1.7321]])
tensor([[0.5774, 0.5774],
        [0.5774, 0.5774]])
tensor([[1.7321, 1.7321],
        [1.7321, 1.7321]])


In [166]:
a=torch.rand(2,2)
print(a)
print(torch.exp(a))#e**a
torch.log(a)

tensor([[0.4463, 0.2846],
        [0.0529, 0.9397]])
tensor([[1.5626, 1.3292],
        [1.0544, 2.5591]])


tensor([[-0.8067, -1.2567],
        [-2.9384, -0.0622]])

In [4]:
a=torch.tensor(3.14)
a.floor(),a.ceil(),a.trunc(),a.frac()

(tensor(3.), tensor(4.), tensor(3.), tensor(0.1400))

In [172]:
a=torch.tensor(3.14)
#四舍五入
a.round()
b=torch.tensor(6.74)
#四舍五入
b.round()

tensor(7.)

In [179]:
grad=torch.rand(2,3)*15
print(grad)
print(grad.max(),grad.median())
print(grad.clamp(6,10))

tensor([[ 2.4147,  8.8985, 10.6381],
        [13.3255,  1.1394,  6.2551]])
tensor(13.3255) tensor(6.2551)
tensor([[ 6.0000,  8.8985, 10.0000],
        [10.0000,  6.0000,  6.2551]])


In [188]:
#属性统计
#norm求范数
a=torch.tensor([[2,3],[6,3]])
print(a)
print(a.prod())#prod累积
print(a.sum())#求和
print(a.argmax())
print(a.argmin())#获取打平后的相应的索引
print(a.argmax(dim=1))
print(a.max(dim=1))

tensor([[2, 3],
        [6, 3]])
tensor(108)
tensor(14)
tensor(2)
tensor(0)
tensor([1, 0])
torch.return_types.max(
values=tensor([3, 6]),
indices=tensor([1, 0]))


In [3]:
import torch
a=torch.linspace(-50,50,15)
print(a)
torch.sigmoid(a)

tensor([-5.0000e+01, -4.2857e+01, -3.5714e+01, -2.8571e+01, -2.1429e+01,
        -1.4286e+01, -7.1429e+00,  4.7684e-07,  7.1429e+00,  1.4286e+01,
         2.1429e+01,  2.8571e+01,  3.5714e+01,  4.2857e+01,  5.0000e+01])


tensor([1.9287e-22, 2.4399e-19, 3.0866e-16, 3.9047e-13, 4.9396e-10, 6.2487e-07,
        7.8987e-04, 5.0000e-01, 9.9921e-01, 1.0000e+00, 1.0000e+00, 1.0000e+00,
        1.0000e+00, 1.0000e+00, 1.0000e+00])