In [12]:
import torch
li = [[1,2,3,4,5,6,7,8,9],[2,3,4,1,4,5,6,2,4]]
li=torch.Tensor(li)
li=li.view(2,3,3)
print(li.shape)
print((li))
li=li.unsqueeze(1)
print(li.shape)
print((li))



torch.Size([2, 3, 3])
tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]],

        [[2., 3., 4.],
         [1., 4., 5.],
         [6., 2., 4.]]])
torch.Size([2, 1, 3, 3])
tensor([[[[1., 2., 3.],
          [4., 5., 6.],
          [7., 8., 9.]]],


        [[[2., 3., 4.],
          [1., 4., 5.],
          [6., 2., 4.]]]])


In [73]:
import torch
from torch.utils.data import DataLoader, Dataset
import numpy as np
import csv
import glob
import os
import random
from torchvision import  datasets
from torchvision import transforms     #变换器
import pandas as pd
#存放数据集的数据
def k():
            featuredatas = []
            datas,labels = [], []
            #在这里获取每条原始记录
            df = pd.read_csv('UNSW-datas/rawnetdata1.csv')
            print(df)
            #将Df中数据按照每行存入列表featuredatas[]
            for idx in range (len(df)):
                # hx=df.index[idx]
                # print('hx:',hx)
                hx=df.loc[df.index[idx]].values.tolist()        #获取每一行
                print('hx:',hx)
                featuredatas.append(hx)                         #每一行存入列表
                datas.append( hx[0:-1])
                labels.append(hx[-1])
            print(len(featuredatas),featuredatas)
            print(len(datas),datas)
            print(len( labels), labels)

k()

     id       dur proto service state  spkts  dpkts  sbytes  dbytes  \
0     1  0.000011   udp       -   INT      2      0     496       0   
1     2  0.000008   udp       -   INT      2      0    1762       0   
2     3  0.000005   udp       -   INT      2      0    1068       0   
3     4  0.000006   udp       -   INT      2      0     900       0   
4     5  0.000010   udp       -   INT      2      0    2126       0   
5     6  0.000003   udp       -   INT      2      0     784       0   
6     7  0.000006   udp       -   INT      2      0    1960       0   
7     8  0.000028   udp       -   INT      2      0    1384       0   
8    30  1.434166   tcp       -   FIN     10      6     530     268   
9    36  0.983874   tcp    http   FIN     10      8     816    1172   
10  171  9.492497   tcp       -   REQ     12      0     540       0   

             rate  ...  ct_dst_sport_ltm  ct_dst_src_ltm  is_ftp_login  \
0    90909.090200  ...                 1               2             0   

In [61]:
ar = np.random.rand(4900).reshape(100,49)
print(ar)
df1 = pd.DataFrame(ar)
df = pd.read_csv('readydata1.csv',header=None)
print(df)
print(df1)
li=[]
for i in range(100):
    x = random.randint(0, 9)
    li.append(x)
print(len(li))
print(li)
df1['49']=li
print(df1)
df1.to_csv('readydata1.csv')
print('finifished')

[[0.42946373 0.3936503  0.75105928 ... 0.35891324 0.46994668 0.87625277]
 [0.55971957 0.97473212 0.34116689 ... 0.55662181 0.97667066 0.34368641]
 [0.14277453 0.98605351 0.17186584 ... 0.54979697 0.11932211 0.26369446]
 ...
 [0.84225555 0.01096763 0.9661556  ... 0.49071707 0.59830347 0.90547757]
 [0.62255078 0.57465596 0.25756591 ... 0.22082727 0.97411955 0.22871396]
 [0.66697025 0.9404533  0.48437831 ... 0.98269836 0.03830577 0.98967097]]
     0    1    2    3    4    5    6    7    8    9   ...   40   41   42   43  \
0   152   59   46  144  228   52  170   74  165  220  ...  129  204  243  153   
1    81  218  110  211   22   90   72   32   12  172  ...  108   48  130  213   
2   172   40   98   49  132  226   21  151   66  130  ...  121   92  244   90   
3   199   47  217  196  107   15   78  103   46    2  ...  120   17  175  151   
4    49   39   58  247   11  125  233   41    1  138  ...  232  155  229  240   
..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  .

PermissionError: [Errno 13] Permission denied: 'netdata2.csv'

In [62]:
ar = np.random.rand(49).reshape(7,7)
df1 = pd.DataFrame(ar)
print(df1)
df = pd.read_csv('readydata1.csv',header=None)
print(df)
datas, labels = [], []
for idx in range (len(df1)):
    hx=df1.loc[df1.index[idx]] #获取每一行
    print('hx')
    print(hx)
    hx =list(hx)
    print(hx)
    hx = list(map(float, hx))
    print(hx)
    print(hx[0:-1])
    listdata=hx[0:-1]

    print('listdata:',listdata)
    datas.append(listdata)
    labels.append(int(hx[-1]))
print("==================")
print(datas)
print('==================')
print(labels)

          0         1         2         3         4         5         6
0  0.273337  0.750580  0.880366  0.512351  0.530710  0.719298  0.150078
1  0.723896  0.966067  0.539577  0.355593  0.525688  0.570082  0.241992
2  0.104759  0.483476  0.229382  0.459356  0.566756  0.671958  0.544591
3  0.835934  0.727308  0.779750  0.497325  0.732625  0.016993  0.370881
4  0.303252  0.366355  0.699258  0.428245  0.213519  0.774363  0.424849
5  0.629447  0.637904  0.433480  0.987916  0.721906  0.188997  0.695642
6  0.140619  0.638432  0.968402  0.652512  0.548308  0.013608  0.947493
     0    1    2    3    4    5    6    7    8    9   ...   40   41   42   43  \
0   152   59   46  144  228   52  170   74  165  220  ...  129  204  243  153   
1    81  218  110  211   22   90   72   32   12  172  ...  108   48  130  213   
2   172   40   98   49  132  226   21  151   66  130  ...  121   92  244   90   
3   199   47  217  196  107   15   78  103   46    2  ...  120   17  175  151   
4    49   39   58  

In [75]:
datas,labels = [], []
with open(os.path.join('UNSW-datas', 'readydata1.csv')) as f:
                    reader = csv.reader(f)
                    for row in reader:
                        data,label = row[0:-1],row[-1]
                        print('data:',data)
                        print('label:',label)
                        label = int(label) #注意思label眼转换为int
                        labels.append(label)
                        datas.append(data)
                    print(labels)
                    print(datas)

data: ['22.0', '114.0', '17.0', '158.0', '142.0', '116.0', '48.0', '32.0', '25.0', '202.0', '6.0', '68.0', '244.0', '142.0', '22.0', '67.0', '103.0', '11.0', '132.0', '209.0', '153.0', '239.0', '242.0', '56.0', '34.0', '62.0', '80.0', '44.0', '117.0', '184.0', '27.0', '30.0', '23.0', '73.0', '59.0', '111.0', '15.0', '72.0', '117.0', '118.0', '98.0', '81.0', '169.0', '181.0', '129.0', '17.0', '138.0', '16.0', '100.0']
label: 6
data: ['88.0', '56.0', '44.0', '239.0', '98.0', '245.0', '220.0', '122.0', '149.0', '120.0', '93.0', '185.0', '251.0', '233.0', '65.0', '72.0', '36.0', '35.0', '48.0', '222.0', '241.0', '190.0', '97.0', '42.0', '157.0', '166.0', '138.0', '140.0', '12.0', '26.0', '2.0', '66.0', '151.0', '209.0', '121.0', '124.0', '183.0', '237.0', '88.0', '103.0', '62.0', '43.0', '17.0', '229.0', '11.0', '127.0', '96.0', '222.0', '27.0']
label: 6
data: ['6.0', '129.0', '89.0', '115.0', '203.0', '210.0', '112.0', '85.0', '230.0', '69.0', '169.0', '139.0', '147.0', '170.0', '78.0', '

In [71]:
a=torch.randn(1,0)
print(a.shape)
print(a)
a
b=torch.tensor(2.1)
print(b.shape)
print(b)

torch.Size([1, 0])
tensor([], size=(1, 0))
torch.Size([])
tensor(2.1000)


In [79]:
li = [2,3,4,5,5,4,5,6,3,4,2,3,4,5,5,6,7]
it = iter(li)
for i in range(10):
    y = next(it,'-1')
    print(y)


2
3
4
5
5
4
5
6
3
4
